[tox]
envlist =
    py{312,313}-django{52}
    flake8

[testenv]
setenv =
    PYTHONPATH = {envsitepackagesdir}/taggit_labels
commands = pytest tests {posargs}
deps =
    django52: Django~=5.2
    pytest-django
package = wheel

[testenv:flake8]
basepython=python
deps = flake8
commands =
    flake8 src/taggit_labels
