[tox]
envlist =
    py{312}-django{52}
    flake8

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/taggit_labels
commands = py.test {posargs}
deps =
    django52: Django~=5.2
    -r {toxinidir}/requirements-test.txt

[testenv:flake8]
basepython=python
deps=flake8
commands=
    flake8 taggit_labels
